### ISSUE TITLE
Working with fields in stead of model with Livewire model

### ISSUE THREAD

**Issue by uteq** [uteq/laravel-move#2]
The biggest problem right now is that all data is stored both in the field as a value and on the model as an attribute. Livewire works with models, but not perfectly. This would take away a lot of code that tries to keep the model in 'sync' with the fields. This way the model would only need to be updated after the user hits 'save' and because the entire resource part is abstract in itself and the end user will not see this, it would not be a problem if the code is not a 100% user friendly.

**Comment by nathanjansen** [comment]
Was fixed in v0.1.0
